## PyTorch_Getting_Started

---

### Note: 
Original source code is from PyTorch Tutorials.  
 - http://pytorch.org/tutorials/index.html  
   
These codes are for python3.  
(Add a bit change, and most of them probably can run with python2)  
Please install Numpy, PyTorch and other libraries before trying to use codes on your computer.    

---

### Contents
- Tensors
- Operations
- Converting Numpy Array <-> torch Tensor

---

In [19]:
# Libraries
import numpy as np
import torch

# for python2
# from __future__ import print_function

### Tensors

In [20]:
a = torch.Tensor(4, 3)
print(a)
b = torch.rand(3, 5)
print(b)


 0.0000e+00 -0.0000e+00  0.0000e+00
-0.0000e+00  9.1783e-35  1.4013e-45
 1.1771e-43  8.4078e-42  0.0000e+00
-0.0000e+00  1.3592e+19  2.7837e-40
[torch.FloatTensor of size 4x3]


 0.6133  0.2062  0.0156  0.7510  0.4168
 0.4910  0.1803  0.5962  0.0310  0.4294
 0.3287  0.8615  0.5831  0.7689  0.8393
[torch.FloatTensor of size 3x5]



In [21]:
print(a.size())

torch.Size([4, 3])


### Operations

In [22]:
# Addition
c = torch.Tensor(3,4)
d = torch.rand(3,4)
print(c)
print(d)
print(c + d)


 0.0000e+00 -0.0000e+00  1.6631e+19  4.6577e-10
 1.0354e-30  1.4013e-45  7.3085e-35  1.4013e-45
 7.3086e-35  1.4013e-45  1.6628e+19 -1.0845e-19
[torch.FloatTensor of size 3x4]


 0.1331  0.7929  0.5171  0.2744
 0.3289  0.2833  0.6245  0.1268
 0.8952  0.7020  0.1322  0.8609
[torch.FloatTensor of size 3x4]


 1.3311e-01  7.9292e-01  1.6631e+19  2.7441e-01
 3.2889e-01  2.8327e-01  6.2449e-01  1.2679e-01
 8.9518e-01  7.0205e-01  1.6628e+19  8.6091e-01
[torch.FloatTensor of size 3x4]



In [23]:
# other syntax 1
print(torch.add(c, d))

# other syntax 2
result = torch.Tensor(c.size())
torch.add(c, d, out=result)
print(result)


 1.3311e-01  7.9292e-01  1.6631e+19  2.7441e-01
 3.2889e-01  2.8327e-01  6.2449e-01  1.2679e-01
 8.9518e-01  7.0205e-01  1.6628e+19  8.6091e-01
[torch.FloatTensor of size 3x4]


 1.3311e-01  7.9292e-01  1.6631e+19  2.7441e-01
 3.2889e-01  2.8327e-01  6.2449e-01  1.2679e-01
 8.9518e-01  7.0205e-01  1.6628e+19  8.6091e-01
[torch.FloatTensor of size 3x4]



In [24]:
# Addition in-place
e = torch.rand(d.size())
print(d)

d.add(e)
print(d)

# operation with an "_" will change tensor.
d.add_(e)
print(e)


 0.1331  0.7929  0.5171  0.2744
 0.3289  0.2833  0.6245  0.1268
 0.8952  0.7020  0.1322  0.8609
[torch.FloatTensor of size 3x4]


 0.1331  0.7929  0.5171  0.2744
 0.3289  0.2833  0.6245  0.1268
 0.8952  0.7020  0.1322  0.8609
[torch.FloatTensor of size 3x4]


 0.5169  0.1375  0.1492  0.5506
 0.8289  0.9273  0.4016  0.3451
 0.3559  0.1218  0.2840  0.4282
[torch.FloatTensor of size 3x4]



In [28]:
# You can use numpy-like indexing.

f = torch.rand(3, 5)
print(f)
print(f[:, 2])
print(f[-1,:])


 0.4265  0.8838  0.1292  0.3227  0.5040
 0.5206  0.9144  0.6112  0.4042  0.2336
 0.6662  0.4924  0.0223  0.3493  0.4468
[torch.FloatTensor of size 3x5]


 0.1292
 0.6112
 0.0223
[torch.FloatTensor of size 3]


 0.6662
 0.4924
 0.0223
 0.3493
 0.4468
[torch.FloatTensor of size 5]



---

### Converting Numpy Array <-> torch Tensor

In [31]:
g = torch.ones(4)
print(g)


 1
 1
 1
 1
[torch.FloatTensor of size 4]



In [34]:
# torch Tensor to numpy Array
h = g.numpy()
print(h)

[ 1.  1.  1.  1.]


In [39]:
g.add_(1)
print(g)
print(h)


 2
 2
 2
 2
[torch.FloatTensor of size 4]

[ 2.  2.  2.  2.]


In [46]:
# numpy Array to torch Tensor

i = np.random.rand(2, 3)
print(i)

j = torch.from_numpy(i)
print(j)
print("value of j[0, 0] is ", j[0,0])

[[ 0.23858292  0.89265807  0.086246  ]
 [ 0.54225071  0.31392856  0.97159074]]

 0.2386  0.8927  0.0862
 0.5423  0.3139  0.9716
[torch.DoubleTensor of size 2x3]

value of j[0, 0] is  0.23858292330910946
